include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    use_key_in_widget_constructors: true
    always_specify_types: true
    prefer_final_locals: true