// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFqpvm88IaKNu-cqkpYt1PLCu467EPsLM',
    appId: '1:972939191921:web:64f973322e1c7e31d65dd0',
    messagingSenderId: '972939191921',
    projectId: 'payfussion-f8d99',
    authDomain: 'payfussion-f8d99.firebaseapp.com',
    storageBucket: 'payfussion-f8d99.firebasestorage.app',
    measurementId: 'G-JCMZ6DV6XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnfoN75FQOD3p10ZLhhY9lvz7-kPM0NPs',
    appId: '1:972939191921:android:6186cc1d7ad6eecfd65dd0',
    messagingSenderId: '972939191921',
    projectId: 'payfussion-f8d99',
    storageBucket: 'payfussion-f8d99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-amm1elUdbiIYnjjhgsEPeyCz6ouTpGM',
    appId: '1:972939191921:ios:59f9b19b34dd956fd65dd0',
    messagingSenderId: '972939191921',
    projectId: 'payfussion-f8d99',
    storageBucket: 'payfussion-f8d99.firebasestorage.app',
    iosBundleId: 'com.example.payfussion',
  );
}
